### ISSUE TITLE
Training/Test Set Calculation

### ISSUE THREAD

**Issue by tom-bu** [ruili3/dynamic-multiframe-depth#2]
I was reading your preprocess_kitti_extract_annotated_depth.py. It's essentially the same as the Monorec script. But I noticed that the train/test numbers in your paper (13666/8634) are different from those in Monorec's paper (13714/8634). I was wondering if the difference in calculation is mentioned somewhere.

**Comment by ruili3** [comment]
Your observation is quite detailed :) 
1. As for `preprocess_kitti_extract_annotated_depth.py`: In the previous version of MonoRec, there is a mismatch between the image index and the GT depth index of Sequence 08. I corrected it and rename the file to differentiate it from MonoRec's version. But now seems MonoRec also fixed this issue, so just feel free to use any of the scripts as long as the depth maps are unzipped into the right folder as shown in my post.

3. Regarding different training samples. The KITTI improved GT depth is computed by accumulating lidar points using 5 adjacent frames. So when using GT depth to train the model, we need to filter out the first 5 and last 5 frames since there is no depth GT maps for those frames. But MonoRec uses self-supervised training, so it only needs to filter the first 1 and the last 1 frame. The inconsistency comes from the data end, as we have `5*2 - 1*2 = 8` frames fewer than MonoRec for each sequence, leading to a total of `6*8=48` (which is `13714-13666`) frames fewer than MonoRec.

**Comment by tom-bu** [comment]
Thank you for the clear explanation!
