### ISSUE TITLE
Evaluation results

### ISSUE THREAD

**Issue by Sungmin-Woo** [ruili3/dynamic-multiframe-depth#7]
Hi @ruili3 , thank you for sharing the great code!
I have verified that the model performance is same with the paper when I use the pretrained weights you provided.
However, when I train the model from scratch, the performance seems to be a little bit lower.
Did you use different training recipe to obtain the best performance (given weights)?
If so, it will be very helpful if you provide some hints regarding what configuration I should change.
I'm looking forward to your reply!

**Comment by ruili3** [comment]
Hi Shungmin,

Thanks for your interest in our work! We use the same script to train our model, and there are very slight fluctuations in performance for different training runs, with possible, slightly _higher/lower_ performances. 

Regarding your question, you can consider starting another training run for a sanity check to see if the performance fluctuates with potentially better scores. If the gap still exists, you can check if the environment and lib versions match the recommended ones, since the different versions may lead to unknown inconsistencies which are a bit hard to locate.

**Comment by Sungmin-Woo** [comment]
Thanks for the detailed explanation!
