### ISSUE TITLE
About High resolution evaluation

### ISSUE THREAD

**Issue by kewangtt** [ruili3/dynamic-multiframe-depth#8]
Dear author,

I noticed you just provide the model parameters of the medium-resolution model.

Could you release the HR model and corresponding evaluating script?

Best regards

Ke

**Comment by ruili3** [comment]
Dear Ke,

Thanks for the question. You can access the HR model (ie, 352x1216) via this [link](https://drive.google.com/file/d/1X8YRA--LBDUNLXTy-snk2_e_L3CUKFWO/view?usp=sharing). Due to the lack of HR motion masks for evaluation, you'll need to rescale the MR moving object mask to align the height of HR resolution and pad the remaining areas with zeros. The current code lacks this part due to limited accessibility to the original codebase.

Hope it can help you :)
